### ISSUE TITLE
Is there something wrong with the white paper?

### ISSUE THREAD

**Issue by duncanwang** [bancorprotocol/contracts-solidity#259]
![whitepaper P11](https://user-images.githubusercontent.com/15844058/47961682-a974b580-e04a-11e8-9337-e3fe8aeb3822.png)

I guess the forum is wrong in whitepaper P11 as cited aboved. 
The forum should be 
connected tokens paid out = Balance ×（1 - （1 - Token_Paid / Supply）^ （1 / CW））

I can verify this with a sample.
![whitepaper P11](https://user-images.githubusercontent.com/15844058/47961715-446d8f80-e04b-11e8-8c73-51102a0ea653.png)

When the buyer sold  19.803902718556966005644821804556 smart token, how many connected token will he received?
with your forum : 
connected tokens paid out = balance ×  ( (1 + tokens destroyed / supply ) ^ (1/CW)− 1)
                                            = (250+10) × ( (1+19.803902718556966005644821804556/(1000 + 19.803902718556966005644821804556)) ^ (1/0.5) - 1) 
                                            = 260 * ((1+19.803902718556966005644821804556/1019.8039027185569660056448218046)^2 -1 )
                                            = 260  × (1.01941932430907984037918767134177 ^ 2  - 1)
                                            = 260 × 0.0392157587747808999782891469054
                                            = 10.196097281443033994355178195405
with my forum:
connected tokens paid out = Balance ×（1 - （1 - tokens destroyed / Supply）^ （1 / CW））
                                            = (250+10) ×  (1 - (1 - 19.803902718556966005644821804556 /(1000 +19.803902718556966005644821804556)^ （1 / 0.5） ))
                                            = 260 ×  （1 - 0.98058067569092015962081232865823 ^ 2）
                                            = 260   ×  (1 -  0.96153846153846153846153846153846)
                                            = 260 × 0.03846153846153846153846153846154
                                            = 9.9999999999999999999999999999994

my forum is more closer.

If you try to convert 750 units of the connected token into Smart Tokens, and then convert back, you'll 
find the big difference.

**Comment by barakman** [comment]
@duncanwang:

From `/contracts/solidity/python`, run this Python script:
```
from FormulaNativePython import calculatePurchaseReturn
from FormulaNativePython import calculateSaleReturn

from decimal import Decimal
from decimal import getcontext
getcontext().prec = 80 # 78 digits for a maximum of 2^256-1, and 2 more digits for after the decimal point

supply = 1000
balance = 250
weight = 500000
amount = 10

newAmount = calculatePurchaseReturn(supply, balance, weight, amount)
oldAmount = calculateSaleReturn(supply + newAmount, balance + amount, weight, newAmount)

print(amount)
print(newAmount)
print(oldAmount)
```
The printout is:
```
10
19.803902718556966005644821804556397912754189219919281516994160885186726412444800
9.9999999999999999999999999999999999999999999999999999999999999999999999999999822
```
Therefore:
1. There is something wrong in your calculations of the white-paper formula.
2. Your formula is less accurate than the white-paper formula.

**Comment by barakman** [comment]
@duncanwang:

UPDATE 2:

Your calculations are correct, but you have used the wrong definition for some of the variables in our formula.

In the white-paper, the values of `tokens paid out` and `tokens destroyed` in the Sell formula are considered negative.

When you wrote your formula, you probably relied on these values being positive.

Since our implementation is based on `unsigned` (i.e., non-negative) arithmetic, we also needed to rely on positive value, and so we inverted the sign of each one of these two variables (see the documentation of function `calculateSaleReturn` in [BancorFormula.sol](https://github.com/bancorprotocol/contracts/blob/master/solidity/contracts/converter/BancorFormula.sol)).

Therefore, your formula is identical to the one implemented in our contract (and to the one given in the white-paper).

Thank you for bringing this up.
