### ISSUE TITLE
Formula reverts

### ISSUE THREAD

**Issue by osarrouy** [bancorprotocol/contracts-solidity#287]
I'm working on integrating the BancorFormula for some emergent organization scheme and it happens that the formula's computation functions reverts in some situations. For instance if it try to call `calculateSellReturn` with the following values `formula.calculateSaleReturn(1000, 100, 100000, 999)` it throws a `revert` error.

Unless this is a mistake from my side I feel like this is pretty tricky cause it means the market maker is not totally liquid ...

**Comment by barakman** [comment]
@osarrouy: Hi.

This is not a mistake on your side, since each input parameter by itself is well within a valid range.

However, the conversion formula is designated to support only a finite number of input combinations, namely, combinations that are "reasonably within the range".

For example in your case, you are trying to sell 99.9% of the total supply, which may well be considered as a non-reasonable scenario.

The reason for this limitation is first and foremost the fact that the number of possible input combinations is larger than the number of possible outputs by an unimaginable magnitude.

Consider the specific function at hand:
```
function calculateSaleReturn(uint256, uint256, uint32, uint256) public view returns (uint256)
```
As you can see, the total number of possible input combinations is `2 ^ (256 + 256 + 32 + 256)`, or simply `2 ^ 800`, while the total number of outputs is `2 ^ 256`.

This means that on average, every output is reached by `2 ^ 544` different input combinations, a fact which implies that most input combinations would likely yield a very inaccurate result.

Our function is therefore not designated to **accurately handle** every possible input.
It simply can't do that, even theoretically (let alone practically).

This function is designated to give a very accurate result for a range of **reasonable** input combinations.

For example, it is highly unlikely that a single user would own 99.9% of the total supply, and even more unlikely for such user to sell all of that in a single transaction (ask yourself who would ever buy that under such scenario).

Your feedback here is well appreciated.
Please feel free to provide more, and moreover, please feel free to correct us if you believe that we have failed to properly address your inquiry.

Thanks

**Comment by osarrouy** [comment]
Hi @barakman,

Thanks a lot for your detailed answer [really] ! I think I do understand the explanation though i'm not sure to fully accept the rational:

 1. Because the `Bancor Formula' is not an injective function: different input can lead to the same output [for instance as long as `balance / supply` has the same ratio] so my guess was that whatever happens there would not be `2 ^800` 'real possible inputs' :)
 2. I would have imagine that the number of possible inputs and their mapping to the range of possible outputs would have been simplified by rounding [which Solidity kind of force us to do anyhow] and not by reverting.

That being said I know by experience that it's almost impossible to fully cover complex mathematical functions in solidity so ... To be honest I've tried to figure out in which functions [and why / how] the function did revert and didn't really achieve to do so :)

My question would thus be: would you have any hint about the range to keep the input into to make sure the functions do not revert? I ask because the use case we're implementing [basically a DAICO mechanism based on the `Bancor Formula` and a `Tap` system] will allow users to 'slowly' withdraw funds out of the collateral pool to fund their project. The price of the bonded token will consequently go down seconds after seconds [as the collateral balance will go down] if no one else invest. We would just like to make sure that, whatever happens, investors are gonna be able to redeem their bonds [even for a low price], which means: the function will not revert :) To do so we can enforce some kind of floor on the tap system but have a hard time figure out what that floor should be based on the formula's functions limitations [what range of input are they able to handle].

Thanks a lot again for your answer.

**Comment by barakman** [comment]
@osarrouy: You're welcome :)

With regards to #1, you are correct. That's why I wrote "on average" (though I admit that perhaps this term is incorrect when used under the purely mathematical aspect).
With regards to #2, you could make the exact same argument about the input, so your point about much fewer than `2 ^ 800` different outputs is also a valid argument for saying that there are much fewer than `2 ^ 256` different inputs.

That said, my overall point (which applies to both of your arguments) is that it is impossible to accurately handle every possible output, when the input range is much smaller. Of course, it ultimately comes down to your definition of *accuracy* (for example, you may not care much if we return `1` when the real answer is `2` because the absolute difference is only 1 wei, or you may actually care a lot because the relative difference is 50%).
If you're interested, then we have added in our repository [a rather large set of tests](https://github.com/bancorprotocol/contracts/tree/master/solidity/python) designated for measuring the accuracy of our formula under various use-cases.

As to your actual question.
First, allow me to say that this is a good question.
We do not have a simple set of conditions which can be used in order to determine whether or not the formula will revert on a given input.

There is one preliminary condition which you may test beforehand:
- For `calculatePurchaseReturn`, verify that `_depositAmount + _connectorBalance < MAX_NUM` before calling the function
- For `calculateSaleReturn`, verify that `_supply < MAX_NUM` before calling the function
- For `calculateCrossConnectorReturn`, verify that `_fromConnectorBalance + _amount < MAX_NUM` before calling the function

This condition may help you eliminating some illegal inputs.
But specifically for your example from the beginning of this thread, it would not.

So I'm not sure that I have an out-of-the-box solution for you on this one.
However, I noticed that you wrote in your description `will allow users to 'slowly' withdraw funds`.
This is quite the opposite of the example that you gave, where a user sells almost the entire supply (i.e., withdraws almost the entire reserve). So I am not quite sure how this example of yours "aligns" with that requirement. Our formula is in fact very much designated for this type of model, i.e., gradual buy & sell.
I think that generally speaking, nothing should revert if you buy less than P% of the total reserve, or sell less than Q% of the total supply. The values of P and Q depend on your connector-weight of course, so if it's constant on your system (e.g., 100K), then I might be able to find them for you (and for this specific weight, I am pretty sure that both P and Q are large enough for fully supporting gradual buy & sell).

I understand that you'd want to incorporate the code in your project (instead of using our `BancorFormula` contract deployed on mainnet, which you could also do by the way).

If that is indeed the case, then here are a few more tips which can help you to tweak it for your own purpose:
1. Note that the first 32 entries in the `maxExpArray` array are masked out. This was applied in order to reduce the number of iterations in the binary-search conducted on this array (function `findPositionInMaxExpArray`), for the purpose of reducing gas-consumption. If you care less about the gas and more about the size of valid input range, then you may enable these entries. Please note that in order to keep the Python testing infrastructure functioning correctly, you will also have to apply it [here](https://github.com/bancorprotocol/contracts/blob/master/solidity/python/FormulaSolidityPort/__init__.py), and in order to keep the Javascript testing infrastructure functioning correctly, you will also have to apply it [here](https://github.com/bancorprotocol/contracts/blob/master/solidity/test/helpers/FormulaConstants.js) (specifically, update the value of `module.exports.MIN_PRECISION`).
2. We have auto-generated large portions of this contract using the Python scripts in [this folder](https://github.com/bancorprotocol/contracts/tree/master/solidity/python/AutoGenerate). All of these scripts depend on the constants value in [this file](https://github.com/bancorprotocol/contracts/blob/master/solidity/python/AutoGenerate/common/constants.py). If you happen to know your system requirements, then it may help you to reconfigure these constants in order to tailor-make the `BancorFormula` contract optimized under those requirements. There are of course a lot of technical details here which I would have to go into, and the term *optimized* by itself has two different interpretations - accuracy & performance - which are typically in "collision" with each other (i.e., improving one hinders the other). So I will not go into it here, but if you do happen to find this option relevant, then I'd be happy to dive into it and help you "reconfiguring" the contract to your needs.

Thanks :)
